#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.jsx" "*.ts" "*.tsx" "*.json" "*.vue" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Run prettier on all files that matched
echo "$FILES" | xargs ./node_modules/.bin/prettier --write
# Re-stage the prettified files
echo "$FILES" | xargs git add

exit 0
